/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.ui.tests;

import com.google.inject.Injector;
import emobility.textual.emdsl.ui.internal.EmdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EmDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EmdslActivator.getInstance().getInjector("emobility.textual.emdsl.EmDsl");
	}

}
