/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EmDslUiModule extends AbstractEmDslUiModule {

	public EmDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
