/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEmDslScopeProvider extends DelegatingScopeProvider {
}
