/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.ui;

import com.google.inject.Injector;
import emobility.textual.emdsl.ui.internal.EmdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EmDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EmdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EmdslActivator activator = EmdslActivator.getInstance();
		return activator != null ? activator.getInjector(EmdslActivator.EMOBILITY_TEXTUAL_EMDSL_EMDSL) : null;
	}

}
