/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import emobility.textual.emdsl.EmDslRuntimeModule;
import emobility.textual.emdsl.EmDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EmDslIdeSetup extends EmDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EmDslRuntimeModule(), new EmDslIdeModule()));
	}
	
}
