/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EmDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("emobility/textual/emdsl/parser/antlr/internal/InternalEmDsl.tokens");
	}
}
