/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl.parser.antlr;

import com.google.inject.Inject;
import emobility.textual.emdsl.parser.antlr.internal.InternalEmDslParser;
import emobility.textual.emdsl.services.EmDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EmDslParser extends AbstractAntlrParser {

	@Inject
	private EmDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEmDslParser createParser(XtextTokenStream stream) {
		return new InternalEmDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domain";
	}

	public EmDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EmDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
