/*
 * generated by Xtext 2.36.0
 */
package emobility.textual.emdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EmDslStandaloneSetup extends EmDslStandaloneSetupGenerated {

	public static void doSetup() {
		new EmDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
